### PR TITLE
Bugfixes for v1.1.0

### PR DESCRIPTION
**Pull request by ghost**
* Add MATLAB's scientific dataset packages.
* Undeprecate generic property names.
* Fix function boundaries in lookbehind patterns.
* Fix import module highlighting
* Make keyword control end tokens consistent
* Fix readwrite injection selector

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks for this @4086606

Any chance you can review and merge @rlivings39 I can handle the version publishing if needed.

**Comment by thedavidprice** [comment]
Is this one ready for review @SNDST00M?

**Comment by SNDST00M** [comment]
Yup

**Comment by thedavidprice** [comment]
@rlivings39 any chance you have availability?

**Review by rlivings39 — APPROVED** [review]

**Comment by rlivings39** [comment]
Was out on vacation. This looks good to me. Merged

**Comment by thedavidprice** [comment]
Thanks, all! I'll work on the release now. It's an important update. Going to bump the semver minor.

**Comment by thedavidprice** [comment]
Thanks, all! I'll work on the release now. It's an important update. Going to bump the semver minor.

**Comment by thedavidprice** [comment]
done 🚀
- https://atom.io/packages/language-matlab-octave
- https://github.com/thedavidprice/language-matlab-octave/releases/tag/v1.2.0

**Pull request merged**
