### PR TITLE
Sync with mathworks/MATLAB-Language-grammar#38

### PR DESCRIPTION
**Pull request by 4086606**
Per title. This is a full grammar overhaul, so I'll leave the changelog in mathworks/MATLAB-Language-grammar#38.

CC @elpollodiablo84 @thedavidprice

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks @4086606!

@rlivings39 would you be available to review and merge? I'm very very out of the loop these days.

**Comment by 4086606** [comment]
Just adding all the new injection grammars

**Comment by 4086606** [comment]
Injection grammars are broken... this is why I switched to other IDEs

**Comment by rlivings39** [comment]
Will take a look today. Thanks for all the work on the grammar @4086606

**Comment by 4086606** [comment]
Thanks for the prompt response, the pull is working great in Atom 1.57

**Review by rlivings39 — APPROVED** [review]
Looks good to me with some manual testing and spot checks. Are you going to submit a PR to Gimly/vscode-matlab to update the submodule to your new grammar? It needs a manual rev after the PR is accepted to mathworks/MATLAB-Language-grammar.

**Comment by thedavidprice** [comment]
Huge thanks, all 🚀

**Comment by thedavidprice** [comment]
Ah, I suppose next up is publishing a new release. I'll queue it up unless you all say otherwise. 

Doesn't appear to be a breaking change, so assuming the `v1.1.0` tag is appropriate, correct?

**Comment by 4086606** [comment]
Sure, 1.1.0 is fine

**Comment by thedavidprice** [comment]
Done and confirmed!

https://github.com/thedavidprice/language-matlab-octave/releases

**Comment by 4086606** [comment]
Could one of you apply https://github.com/Gimly/vscode-matlab/commits/a5244d92ae1ae05fb0bc20989334bcfcdab8dad5 to this repository? Some super generic properties are being hit by `invalid.deprecated`

**Comment by thedavidprice** [comment]
@4086606 do you mean this commit specifically?
- https://github.com/Gimly/vscode-matlab/commit/a5244d92ae1ae05fb0bc20989334bcfcdab8dad5#diff-fe7c8c932623e7c2a13270e06d5451e21ba566fe25bd439791b4767a5964c179

**Comment by thedavidprice** [comment]
Note: for commit I linked in previous comment, the corresponding line is here:
https://github.com/thedavidprice/language-matlab-octave/blob/ba6fbdbbf0d109871649bcf0d90a3b71ad017164/grammars/m.cson#L1689

**Comment by 4086606** [comment]
Yup, and the commits afterwards if possible

**Comment by thedavidprice** [comment]
Hmm, the link you provided takes me to a page for the branch with the commit I linked at the top of the page. Below that commit, the page lists the entire commit history of the branch.

Screen Shot 2021-07-22 at 5 03 01 PM

**Comment by 4086606** [comment]
My bad try this link:

https://github.com/Gimly/vscode-matlab/pull/132/commits/a5244d92ae1ae05fb0bc20989334bcfcdab8dad5

**Comment by thedavidprice** [comment]
Ok, now I'm seeing the single commit that I attempted to link to originally:

Screen Shot 2021-07-22 at 5 15 33 PM

So looking at the rest of the commit history in that PR, by "and the commits afterward if possible" are you referring to these?

Screen Shot 2021-07-22 at 5 17 24 PM

**Comment by 4086606** [comment]
Yup

**Comment by 4086606** [comment]
I've completed some projects early so I'll open a pull for it

**Pull request merged**
